# Generated by Django 2.1.1 on 2018-10-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiker',
            name='bio',
            field=models.TextField(default='wee', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiker',
            name='social_media',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
