# Generated by Django 2.1.1 on 2018-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181016_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='difficulty',
            field=models.Field(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard'), ('4', 'Advanced'), ('5', 'Extreme')], default='1', max_length=1),
        ),
    ]
