# Generated by Django 2.1.1 on 2018-10-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hiker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hiker',
            name='experience',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Experienced'), ('4', 'Advanced')], default='1', max_length=1),
        ),
    ]
