# Generated by Django 2.1.1 on 2018-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181013_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'other')], max_length=1),
        ),
    ]
