# Generated by Django 2.1.1 on 2018-10-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181013_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
