# Generated by Django 2.1.1 on 2018-10-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20181017_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='hiker',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='difficulty',
        ),
    ]
