# Generated by Django 2.1.1 on 2018-10-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard'), ('4', 'Advanced'), ('5', 'Extreme')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='hiker',
            field=models.ManyToManyField(to='main_app.Hiker'),
        ),
        migrations.AddField(
            model_name='trip',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
