# Generated by Django 2.1.1 on 2018-10-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181015_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trail',
            field=models.ManyToManyField(to='main_app.Trail'),
        ),
    ]
