# Generated by Django 2.1.1 on 2018-10-16 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_trip_trail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='hiker',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
